spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: jwt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: jwt

jwt:
  secret: 4b0fc642773f223f3160bbb44402b4150fc124c5
  duration: 86400000
